# Generated by Django 3.2.15 on 2022-10-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_index_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='handleSignup',
        ),
    ]
