# Generated by Django 3.2.15 on 2022-12-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_index_handlesignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='handledatascience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=13)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='handleSignup',
        ),
    ]
