# Generated by Django 3.2.15 on 2022-12-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20221203_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handledatascience',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='handledatascience',
            name='email',
        ),
        migrations.RemoveField(
            model_name='handledatascience',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='handledatascience',
            name='phone',
        ),
    ]
