# Generated by Django 3.2.15 on 2022-12-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20221208_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
