# Generated by Django 3.2.15 on 2022-12-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact1',
        ),
    ]
