# Generated by Django 3.2.15 on 2022-12-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_contact_contact1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact1',
            new_name='Contact',
        ),
    ]
